### ISSUE TITLE
Web site

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/PyCI#10]
I made the domain `pyci.qcdevs.org`

**Comment by RichRick1** [comment]
Great! I need an admin access to the repo so I can use gh-pages.

**Comment by msricher** [comment]
@RichRick1 You should have admin access now

**Comment by RichRick1** [comment]
Thanks! Website is available now at pyci.qcdevs.org. Go check it out

**Comment by msricher** [comment]
Thanks! I need to add one more thing: The website says PyCI is Lesser GPL licensed, while I put all the license files and texts as "GPLv3".  Can we change your website code to say just "GPL"?

**Comment by RichRick1** [comment]
yup! I'll fix it

**Comment by RichRick1** [comment]
Just to clarify. You want to change this part 
<img width="843" alt="image" src="https://github.com/theochem/PyCI/assets/36164007/b1a5072f-4547-4466-9af2-851f1590eba5">
to GNU LESSER GPL?

**Comment by msricher** [comment]
I want to change it to GNU GPLv3
