### ISSUE TITLE
handling seniorities in low dimensional systems

### ISSUE THREAD

**Issue by paulandrewjohnson** [theochem/PyCI#35]
I'm trying to run seniority 0+2+4 CI for H6. There should be determinants of seniority-4, but it raises:
ValueError: invalid seniority number in seniorities = (0, 2, 4)

Minimal code using H6.FCIDUMP (attached as a .txt)

[H6_2.00.txt](https://github.com/theochem/PyCI/files/14879119/H6_2.00.txt)

```
import pyci

filename = "H6_2.00.FCIDUMP"
occs = (3,3)
ham = pyci.hamiltonian(filename)

seniorities = [0,2,4]
wfn = pyci.fullci_wfn(ham.nbasis, *occs)
pyci.add_seniorities(wfn, *seniorities)

```

**Comment by msricher** [comment]
Hi Paul, you're right, there's a bug where it checks for valid seniorities that shows up with low dimensionality. I'll fix it by tomorrow.

**Comment by paulandrewjohnson** [comment]
Thanks!
