### ISSUE TITLE
FanCI tutorial 

### ISSUE THREAD

**Issue by AlexandreDeCamargo** [theochem/PyCI#40]
After getting from @RichRick1 a FCIDUMP file of a Hubbard model I am getting the values of the cost function, the residuals, the optimality and active_mask equal to zero when optimizing the AP1roG wavefunction. The solution found is:

`x: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
                0.000e+00  0.000e+00  0.000e+00  0.000e+00  3.000e+01]`

Optimizing the pCCD+S wave function give me residuals near zero ($10^{-15}$ order) and a solution x: 

`x: [-1.334e+01  1.334e+01 ... -5.454e-14  3.000e+01]`

**Comment by RichRick1** [comment]
@PaulWAyers I gave @AlexandreDeCamargo 6-site Hubbard model with U=10, so it's a strongly correlated system. I'd expect to have much higher projection error
@msricher is there any system for which AP1roG method will give a big error in energy?

**Comment by PaulWAyers** [comment]
AP1roG should be bad for attractive Hubbard and attractive Richardson.

**Comment by msricher** [comment]
I'm not sure. Is it possible to compare against the FCI energy?
