### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by RichRick1** [theochem/PyCI#43]
There are 6 semidefinite constraints, 3 easy and 3 hard. One could use:
- [ ] #47
- [ ] #48
- [ ] #49
- [ ] #50

For the constraints, the function should be, for example:
```
def calc_P(gamma):
      ...
      return P
```

-----
UPD: all of these can go into the rdm.conditions module which can be found at rdm/conditions.py file

**Comment by PaulWAyers** [comment]
The number of electrons can be given by the user or inferred from the density matrix. I would allow it as an optional argument; if it is not given then the density matrix is used to infer the number of electrons. If the number of electrons is given, then this affects the value of the trace one is enforcing.

**Comment by PaulWAyers** [comment]
So `if n == None then:`
you would compute.

Note that by pep8 standards I am pretty sure that `n` should be lower case. Might be better to name it `n_el` or `n_e` just to be clearer.
