### ISSUE TITLE
finding the closest semidefinite

### ISSUE THREAD

**Issue by RichRick1** [theochem/PyCI#47]
This function can go into the rdm.constraints module which can be found at rdm/constraints.py file

**Comment by manyasha-n-m** [comment]
I have a question about calculating the shift, could you please give me any recommendation? @RichRick1 @PaulWAyers 

<img width="883" alt="Screenshot 2024-04-26 at 10 45 44 AM" src="https://github.com/theochem/PyCI/assets/62342353/9f845070-f775-444a-bfe7-d60b0987ee83">
