### ISSUE TITLE
HIgher-Order Reduced Density Matrices

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/PyCI#58]
It would be nice to have 3- and 4-electron reduced density matrices, especially (perhaps even exclusively) for the seniority-zero case, where the number of indices in these matrices is very small. This might go together with a special implementation for the DMs of seniority-zero wavefunctions.

I'm tentatively tagging @DanielCalero1 on this, as it may be useful for that project. It isn't a super high priority (yet) though.

**Comment by msricher** [comment]
There already exists a special implementation of the {1,2}-RDM for seniority-zero ("DOCI") wave functions [here](https://github.com/theochem/PyCI/blob/9d21b32b681954268fc1e5f7e346174c3566d098/pyci/src/rdm.cpp#L20).

It is definitely feasible to code the 3 and 4 -RDMs for the DOCI wave function class. Like with the 1 and 2 -RDMs, you just need to determine the unique non-zero blocks$`{}^{*}`$, and then evaluate the elements over all pairs of connected determinants.

$`{}^{*}`$Something like AAA, AAB, ..., BBA, BBB for the 3-RDM, and AAAA, ..., BBBB for the 4-RDM.

**Comment by DanielCalero1** [comment]
Sounds good. I'll take a look into it!

**Comment by PaulWAyers** [comment]
Good to make a new issue for DOCI 4RDM.

**Comment by DanielCalero1** [comment]
I'll create one right away!
